// Ovde dodajes iteme, samo prati kako su ostali napisani, ako ne expireuje, napisi na endTime: Infinity, i isto napisi ako je one time use, samo iskoristi removeSpecificItem kad brises item
let shopItems = [
  {
    name: `XP Booster`,
    price: 10000,
    startTime: `now`,
    endTime: `end`,
    emoji: `🔼`,
  },
  {
    name: `Double Challenge Rewards`,
    price: 50000,
    startTime: `now`,
    endTime: `Infinity`,
    emoji: `⏫`,
  },
  {
    name: `Coin Shield`,
    price: 50000,
    startTime: `now`,
    endTime: `hour2`,
    emoji: `🛑`,
  },
  // {
  //   name: `Coin Shield v2`,
  //   price: 100000,
  //   startTime: `now`,
  //   endTime: `hour2`,
  //   emoji: `⛔`,
  // },
  {
    name: `High Roller Pass`,
    price: 150000,
    startTime: `now`,
    endTime: `Infinity`,
    emoji: `🔑`,
  },
  {
    name: `Custom Name License`,
    price: 50000,
    startTime: `now`,
    endTime: `Infinity`,
    emoji: `📃`,
  },
  {
    name: `Change Custom Name`,
    price: 200000,
    startTime: `now`,
    endTime: `Infinity`,
    emoji: `📃`,
  },
  {
    name: `Wealth Multiplier`,
    price: 250000,
    startTime: `now`,
    endTime: `hour1`,
    emoji: `📈`,
  },
  {
    name: `Interest-Free Loan`,
    price: 50000,
    startTime: `now`,
    endTime: `Infinity`,
    emoji: `🏦`,
  },
  {
    name: `Invisible Player`,
    price: 50000,
    startTime: `now`,
    endTime: `hour2`,
    emoji: `👻`,
  },
  {
    name: `XP Stealer`,
    price: 50000,
    startTime: `now`,
    endTime: `end`,
    emoji: `🐱‍👤`,
  },
  {
    name: `Level Jump`,
    price: 150000,
    startTime: `now`,
    endTime: `Infinity`,
    emoji: `⏫`,
  },
  {
    name: `Risk Taker's Badge`,
    price: 50000,
    startTime: `now`,
    endTime: `Infinity`,
    emoji: `📛`,
  },
  {
    name: `XP Converter`,
    price: 100000,
    startTime: `now`,
    endTime: `hour2`,
    emoji: `💱`,
  },
];
module.exports = {
  shopItems,
};
